Generalisations
code-monk08/connect4 pull request #18
Opened 2019-12-09 11:40 UTC by amanpalariya

I have generalised some of the expressions

2019-12-09 21:29 UTC, code-monk08 commented
Awesome! @amanpalariya 
can you look at the code more closely and see if there are few more possibilities of such changes?

2019-12-10 03:43 UTC, amanpalariya commented
Sure

2019-12-10 15:03 UTC, bymayanksingh approved these changes

2019-12-10 15:04 UTC, bymayanksingh approved these changes

2019-12-10 15:11 UTC, bymayanksingh requested changes

2019-12-10 15:11 UTC, code-monk08 commented on game_renderer.py
>          :param board: The game board.
please modify the doc strings as well.

2019-12-10 15:15 UTC, code-monk08 commented
I think after requested change we are good to go with your PR :)
Thanks.

2019-12-11 05:25 UTC, amanpalariya commented on game_renderer.py
>          :param board: The game board.
Done

2019-12-11 05:29 UTC, amanpalariya commented
This time, the game has been optimized to handle different board sizes. The requested change has been applied.

2019-12-11 05:30 UTC, amanpalariya commented
Also, issue #21 has been resolved in this patch

2019-12-11 08:58 UTC, code-monk08 commented
> Also, issue #21 has been resolved in this patch

fix is already merged in #25

2019-12-11 08:59 UTC, code-monk08 commented
we have some conflicts, can you remove them?

2019-12-11 09:13 UTC, amanpalariya commented
Resolved

2019-12-11 09:22 UTC, code-monk08 commented
I think we need some generalizations with font sizes as well, height is increased - we don't really want that, make everything little more consistent, also can you make this resizable on command?

like once the mouse is at the edge of game window, resize icon appears and user can resize, also check if you can give the ability to scale in fixed ratio? (square ratio)

2019-12-11 09:23 UTC, amanpalariya commented on game_renderer.py
> +        """
I used filled circles before I found knew a way to resize images in `pygame`

2019-12-11 09:34 UTC, amanpalariya commented
> I think we need some generalizations with font sizes as well, height is increased - we don't really want that, make everything little more consistent, also can you make this resizable on command?
> 
> like once the mouse is at the edge of game window, resize icon appears and user can resize, also check if you can give the ability to scale in fixed ratio? (square ratio)

I think that I have managed font sizes. Also, the window cannot overflow the screen. I have put a limit to the width and height of the window.

As far as resizability is concerned, I will surely try to manage it. 👍

2019-12-12 02:05 UTC, amanpalariya commented
Please go ahead with this PR. I think I'll handle resizability some other time.

2019-12-14 07:36 UTC, closed without merging